apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis-lettuce-demo
  namespace: argocd
spec:
  generators:
    - list:
        elements:
        - cluster: dev
          url: https://dev-aphid-ag7ava9s.hcp.brazilsouth.azmk8s.io:443
          environment: dev
        - cluster: prod1
          url: https://prod-weevil-jf8xyfdc.hcp.brazilsouth.azmk8s.io:443
          environment: prod1
  template:
    metadata:
      annotations:
        argocd-image-updater.argoproj.io/image-list: myalias=docker.io/zhangchl007/redisdemo
        argocd-image-updater.argoproj.io/myalias.helm.image-tag: image.tag
        argocd-image-updater.argoproj.io/myalias.allow-tags: regexp:^v[1-9].*
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
        argocd-image-updater.argoproj.io/git-branch: main
        argocd-image-updater.argoproj.io/myalias.force-update: "true"
      name: "redisdemo-{{cluster}}"
    spec:
      project: gitops-demo
      source:
        repoURL: "https://github.com/zhangchl007/redis-lettuce-demo-manifests.git"
        targetRevision: HEAD
        path: "gitops-demo/helm-app"
        helm:
          valueFiles:
            - "env/{{environment}}/values.yaml"
      destination:
        server: '{{url}}'
        namespace: "{{environment}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true