apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis-lettuce-demo
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: "https://github.com/zhangchl007/redis-lettuce-demo-manifests.git"
              revision: HEAD
              files:
                - path: "gitops-demo/helm-app/env/*/values.yaml"
          - list:
              elements:
              - cluster: dev
                url: https://dev-gitops-dev-gitops-aks-r-bba32a-e4d7kf15.hcp.westus2.azmk8s.io:443
              - cluster: prod
                url: https://prod-gitop-prod-gitops-aks--bba32a-9y95o74w.hcp.westus2.azmk8s.io:443
  template:
    metadata:
      name: "redisdemo-{{path.basename}}"
    spec:
      project: gitops-demo
      source:
        repoURL: "https://github.com/zhangchl007/redis-lettuce-demo-manifests.git"
        targetRevision: HEAD
        path: "/gitops-demo/helm-app"
        helm:
          valueFiles:
            - "env/{path.basename}}/values.yaml"
      destination:
        server: '{{url}}'
        namespace: "{{path.basename}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true