apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis-lettuce-demo
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: "https://github.com/zhangchl007/redis-lettuce-demo-manifests.git"
              revision: HEAD
              files:
                - path: "gitops-demo/helm-app/env/*/values.yaml"
          - list:
              elements:
              - cluster: dev
                url: https://dev-gitops-dev-gitops-aks-r-bba32a-e4d7kf15.hcp.westus2.azmk8s.io:443
              - cluster: prod1
                url: https://10.5.16.4:6443
        include:
          - cluster: "{{ path.basename }}"
  template:
    metadata:
      name: "redisdemo-{{path.basename}}"
    spec:
      project: gitops-demo
      source:
        repoURL: "https://github.com/zhangchl007/redis-lettuce-demo-manifests.git"
        targetRevision: HEAD
        path: "gitops-demo/helm-app"  # Remove the leading slash
        helm:
          valueFiles:
            - "env/{{path.basename}}/values.yaml"  # Fix the curly braces
      destination:
        server: '{{url}}'
        namespace: "{{path.basename}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true