apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redisdemo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "{{ .Release.Namespace }}.env.my"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "redisdemo"
                port:
                  number: 8080