apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis-lettuce-demo
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: "https://github.com/zhangchl007/redis-lettuce-demo-manifests.git"
              revision: HEAD
              files:
                - path: "helm-app/env/*/values.yaml"
          - clusters:
              # Adjust the selector as needed to include your clusters (e.g., dev, prod, in-cluster)
              selector:
                matchExpressions:
                  - key: "name"
                    operator: In
                    values:
                      - dev
                      - prod
  template:
    metadata:
      name: "redisdemo-{{path.basename}}"
    spec:
      project: gitops-demo
      source:
        repoURL: "https://github.com/zhangchl007/redis-lettuce-demo-manifests.git"
        targetRevision: HEAD
        path: "helm-app"
        helm:
          valueFiles:
            - "env/{path.basename}}/values.yaml"
      destination:
        server: "{{cluster.server}}"
        namespace: "{{path.basename}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true