apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis
  namespace: argocd
spec:
  generators:
    - list:
        elements:
        - cluster: dev
          url: https://dev-gitops-dev-gitops-aks-r-bba32a-e4d7kf15.hcp.westus2.azmk8s.io:443
          environment: dev
        - cluster: prod1
          url: https://prod-gitop-prod-gitops-aks--bba32a-9y95o74w.hcp.westus2.azmk8s.io:443
          environment: prod1
  template:
    metadata:
      name: "redis-{{cluster}}"
    spec:
      project: gitops-demo
      source:
        repoURL: "https://github.com/zhangchl007/redis-lettuce-demo-manifests.git"
        targetRevision: HEAD
        path: "gitops-demo/helm-infra"
        helm:
          valueFiles:
            - "env/{{environment}}/values.yaml"
      destination:
        server: '{{url}}'
        namespace: "infra-{{environment}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true