apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-example
  namespace: argocd
spec:
  project: gitops-demo
  source:
    repoURL: https://github.com/zhangchl007/redis-lettuce-demo-manifests.git
    targetRevision: HEAD
    path: gitops-demo/kustomize-example/app        # <-- put ONLY the app manifests (not this file) here
  destination:
    server: https://prod-weevil-jf8xyfdc.hcp.brazilsouth.azmk8s.io:443
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# PreSync hook Job (must have metadata.name; generateName breaks kustomize).
# Place this Job in the SAME Argo CD application source (root app-of-apps),
# or move it under kustomize-example/app if you want it to run for that child app instead.
apiVersion: batch/v1
kind: Job
metadata:
  name: opa-scan-kustomize-example
  namespace: argocd
  labels:
    app.kubernetes.io/name: opa-scan-kustomize-example
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: opa-kustomize-scan
          image: alpine:3.19
          command: ["/bin/sh","-c"]
          args:
            - |
              set -euo pipefail
              echo "[INFO] Install tools..."
              apk add --no-cache git curl tar gzip
              CONFTEST_VER=v0.55.0
              KUSTOMIZE_VER=v5.4.2
              curl -sSL https://github.com/open-policy-agent/conftest/releases/download/${CONFTEST_VER}/conftest_${CONFTEST_VER#v}_Linux_x86_64.tar.gz | tar -xz -C /usr/local/bin conftest
              curl -sSL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/${KUSTOMIZE_VER}/kustomize_${KUSTOMIZE_VER}_linux_amd64.tar.gz | tar -xz -C /usr/local/bin kustomize
              echo "[INFO] Cloning repo..."
              git clone --depth 1 --branch "$ARGOCD_APP_SOURCE_TARGET_REVISION" "$ARGOCD_APP_SOURCE_REPO_URL" /src
              echo "[INFO] Rendering kustomize at: /src/gitops-demo/kustomize-example/app"
              kustomize build /src/gitops-demo/kustomize-example/app > /tmp/rendered.yaml
              echo "[INFO] Running conftest (if policies exist)..."
              if [ -d /src/policy ]; then conftest test /tmp/rendered.yaml --policy /src/policy; else echo "No /src/policy directory; skipping custom policies"; fi
              echo "[INFO] Scan passed."