apiVersion: v1
kind: Pod
metadata:
  name: test-privileged
  namespace: default
spec:
  containers:
    - name: c
      image: busybox
      command: ["sleep", "3600"]
      securityContext:
        privileged: true
